import type { ComponentSpec } from "@baby-ui/registry-schema";

/** Third-party notices must live at repo root, not only in a ported component's header. */
export function buildThirdPartyLicenses(specs: ComponentSpec[]): string {
	const bySource = new Map<string, NonNullable<ComponentSpec["licenseOrigin"]>>();

	for (const spec of specs) {
		if (!spec.licenseOrigin) continue;
		bySource.set(spec.licenseOrigin.source, spec.licenseOrigin);
	}

	const lines = [
		"# Third-party licenses",
		"",
		"Generated by `pnpm registry`. Some components in this repository were re-derived from",
		"the projects below: props were re-specified as ComponentSpecs and each framework",
		"implementation was authored against that spec rather than copied. The original",
		"notices are reproduced here as those licenses require.",
		"",
	];

	for (const origin of [...bySource.values()].sort((a, b) =>
		a.source.localeCompare(b.source),
	)) {
		lines.push(
			`## ${origin.source}`,
			"",
			`- Source: ${origin.url}`,
			`- License: ${origin.license}`,
			"",
		);
	}

	if (bySource.size === 0) lines.push("No third-party-derived components yet.", "");
	return lines.join("\n");
}
