import type { ComponentSpec } from "@baby-ui/registry-schema";

/** The MIT notice must live at repo root, not only in a ported component's header. */
export function buildThirdPartyLicenses(specs: ComponentSpec[]): string {
	const bySource = new Map<
		string,
		{ origin: NonNullable<ComponentSpec["licenseOrigin"]>; slugs: string[] }
	>();

	for (const spec of specs) {
		if (!spec.licenseOrigin) continue;
		const entry = bySource.get(spec.licenseOrigin.source);
		if (entry) entry.slugs.push(spec.slug);
		else
			bySource.set(spec.licenseOrigin.source, {
				origin: spec.licenseOrigin,
				slugs: [spec.slug],
			});
	}

	const lines = [
		"# Third-party licenses",
		"",
		"Generated by `pnpm registry`. Components in this repository were re-derived from",
		"the projects below: props were re-specified as ComponentSpecs and each framework",
		"implementation was authored against that spec rather than copied. The original",
		"notices are reproduced here as those licenses require.",
		"",
	];

	for (const { origin, slugs } of [...bySource.values()].sort((a, b) =>
		a.origin.source.localeCompare(b.origin.source),
	)) {
		lines.push(
			`## ${origin.source}`,
			"",
			`- Source: ${origin.url}`,
			`- License: ${origin.license}`,
			`- ${origin.copyright}`,
			`- Components derived: ${slugs.sort().join(", ")}`,
			"",
		);
	}

	if (bySource.size === 0) lines.push("No third-party-derived components yet.", "");
	return lines.join("\n");
}
